
abstract=
ontologyTitle=DAIMO: An ontology for managing AI models in data spaces
ontologyPrefix=daimo
ontologyNamespaceURI=http://purl.org/pionera/daimo#
ontologyName=DAIMO ontology
thisVersionURI=http://purl.org/pionera/daimo/1.0.0
latestVersionURI=
previousVersionURI=
dateCreated=
dateModified=2026-04-04
ontologyRevisionNumber=1.0.0
licenseURI=null
licenseName=null
licenseIconURL=null
citeAs=http://purl.org/pionera/daimo#Edmundo, http://purl.org/pionera/daimo#Jiayun. DAIMO: An ontology for managing AI models in data spaces. Revision: 1.0.0. Retrieved from: http://purl.org/pionera/daimo/1.0.0
DOI=
status=Ontology Specification Draft
logo=
description=Ontology for representing AI models as governed assets in data spaces.
introduction=
backwardsCompatibleWith=
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=http://purl.org/pionera/daimo#Edmundo;http://purl.org/pionera/daimo#Jiayun
authorsURI=;
authorsInstitution=;
authorsInstitutionURI=;
contributors=
contributorsURI=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=
importedOntologyURIs=
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=
seeAlso=
fundingGrants=
funders=
